In [2]:
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt
import time
import mediapipe as mp

# Mediapipe
- Predstavljanje tacaka na slici iz kamere
- Prikupljanje podataka sa slike koji ce se posle koristiti za obucavanje modela

In [3]:
mp_holistics = mp.solutions.holistic
mp_drawing = mp.solutions.drawing_utils

In [4]:
def landmarksOnScreen(image, points):
    #mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistics.FACEMESH_TESSELATION)
    #mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistics.POSE_CONNECTIONS)
    mp_drawing.draw_landmarks(image, points.left_hand_landmarks, mp_holistics.HAND_CONNECTIONS,
                             mp_drawing.DrawingSpec(color=(0,0,255), thickness=2, circle_radius=3),
                             mp_drawing.DrawingSpec(color=(255,0,0), thickness=2, circle_radius=2))
    mp_drawing.draw_landmarks(image, points.right_hand_landmarks, mp_holistics.HAND_CONNECTIONS,
                             mp_drawing.DrawingSpec(color=(255,0,0), thickness=2, circle_radius=3),
                             mp_drawing.DrawingSpec(color=(0,0,255), thickness=2, circle_radius=2))

In [28]:
cap=cv2.VideoCapture(0)
with mp_holistics.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():
        _, image = cap.read()
        
        image= cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image.flags.writeable = False
        points = holistic.process(image)
        image.flags.writeable = True
        image= cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        
        landmarksOnScreen(image, points)
        
        cv2.imshow('OpenCv Feed', image)
        if cv2.waitKey(1) == ord('q') or cv2.getWindowProperty('OpenCv Feed', cv2.WND_PROP_VISIBLE) < 1:
            break;
    cap.release()
    cv2.destroyAllWindows()

- Dobijamo 2 niza od po 21*3 elemenata
- Ukoliko ruka nije vidljiva na ekranu javlja error pa u tim slucajevima hocemo da imamo niz 0 kako bi ulaz uvek bio isti

In [8]:
(np.array(list(map(lambda lm: [lm.x, lm.y, lm.z], points.left_hand_landmarks.landmark)))).flatten()

array([ 4.96447444e-01,  9.46872652e-01, -4.09065876e-07,  5.02255917e-01,
        8.76750529e-01,  7.70489778e-03,  5.36302507e-01,  8.18676114e-01,
        1.11605423e-02,  5.53416014e-01,  7.70415723e-01,  7.53687741e-03,
        5.66418648e-01,  7.25990415e-01,  2.92095053e-03,  6.01096928e-01,
        8.37207139e-01,  2.99426429e-02,  6.22476697e-01,  7.73255885e-01,
        1.52656240e-02,  6.20362997e-01,  7.15505838e-01, -7.62498414e-04,
        6.09354019e-01,  6.71928525e-01, -1.16436845e-02,  6.15548015e-01,
        8.56694460e-01,  1.37518886e-02,  6.32099211e-01,  7.74290740e-01,
       -3.73083190e-03,  6.16259217e-01,  7.18344033e-01, -2.31825877e-02,
        5.98002911e-01,  6.80303454e-01, -3.38877663e-02,  6.22995377e-01,
        8.84981453e-01, -5.00300108e-03,  6.42133236e-01,  7.89296985e-01,
       -2.75965780e-02,  6.17746890e-01,  7.33466387e-01, -4.22201678e-02,
        5.94439387e-01,  6.98588252e-01, -4.77999151e-02,  6.20417595e-01,
        9.17216063e-01, -

In [10]:
landmarkArrayLeft=np.zeros(21*3)
if points.left_hand_landmarks:
    landmarkArrayLeft=(np.array(list(map(lambda lm: [lm.x, lm.y, lm.z], points.left_hand_landmarks.landmark)))).flatten()

In [11]:
landmarkArrayLeft

array([ 4.96447444e-01,  9.46872652e-01, -4.09065876e-07,  5.02255917e-01,
        8.76750529e-01,  7.70489778e-03,  5.36302507e-01,  8.18676114e-01,
        1.11605423e-02,  5.53416014e-01,  7.70415723e-01,  7.53687741e-03,
        5.66418648e-01,  7.25990415e-01,  2.92095053e-03,  6.01096928e-01,
        8.37207139e-01,  2.99426429e-02,  6.22476697e-01,  7.73255885e-01,
        1.52656240e-02,  6.20362997e-01,  7.15505838e-01, -7.62498414e-04,
        6.09354019e-01,  6.71928525e-01, -1.16436845e-02,  6.15548015e-01,
        8.56694460e-01,  1.37518886e-02,  6.32099211e-01,  7.74290740e-01,
       -3.73083190e-03,  6.16259217e-01,  7.18344033e-01, -2.31825877e-02,
        5.98002911e-01,  6.80303454e-01, -3.38877663e-02,  6.22995377e-01,
        8.84981453e-01, -5.00300108e-03,  6.42133236e-01,  7.89296985e-01,
       -2.75965780e-02,  6.17746890e-01,  7.33466387e-01, -4.22201678e-02,
        5.94439387e-01,  6.98588252e-01, -4.77999151e-02,  6.20417595e-01,
        9.17216063e-01, -

In [12]:
landmarkArrayRight=np.zeros(21*3)
if points.right_hand_landmarks:
    landmarkArrayRight=(np.array(list(map(lambda lm: [lm.x, lm.y, lm.z], points.right_hand_landmarks.landmark)))).flatten()

In [13]:
landmarkArrayRight

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
landmarkArray=np.concatenate([landmarkArrayRight, landmarkArrayLeft])

- Dobijeni niz je duzine 2 * 3 * 21=126

In [15]:
landmarkArray

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  

# Prikupljanje podataka
- Kreiramo landmarkArray na gore predstavljeni nacin za ulazne podatke
- Funkcija koja dobijenu sliku pretvara u landmarkArray

In [170]:
letters=['A', 'B', 'V', 'G', 'D', 'Dj', 'E', 'Zj',
         'Z', 'I', 'J', 'K', 'L', 'Lj', 'M', 'N', 
         'Nj', 'O', 'P', 'R', 'S', 'T', 'Cj', 'U',
         'F', 'H', 'C', 'Cz', 'Dz', 'Sj']

In [175]:
for letter in letters:
    try:
        os.makedirs(os.path.join('Azbuka', letter))
    except:
        pass

In [172]:
def buildLandmarkArray(image, holistic):
    image= cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image.flags.writeable = False
    points = holistic.process(image)
    image.flags.writeable = True
    image= cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    landmarkArrayLeft=np.zeros(21*3)
    if points.left_hand_landmarks:
        landmarkArrayLeft=(np.array(list(map(lambda lm: [lm.x, lm.y, lm.z], points.left_hand_landmarks.landmark)))).flatten()
        #print(points.left_hand_landmarks)
    landmarkArrayRight=np.zeros(21*3)
    if points.right_hand_landmarks:
        landmarkArrayRight=(np.array(list(map(lambda lm: [lm.x, lm.y, lm.z], points.right_hand_landmarks.landmark)))).flatten()
        #print(points.right_hand_landmarks)
    return points, np.concatenate([landmarkArrayRight, landmarkArrayLeft])

In [173]:
cap = cv2.VideoCapture(0)

with mp_holistics.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    for letter in letters:
        for imageNum in range(51):
            _, image = cap.read()
            points, landmarkArray = buildLandmarkArray(image, holistic)

            landmarksOnScreen(image, points)
            cv2.putText(image, 'Images for ' + letter + ' num ' + str(imageNum), (30, 30),
                        cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 0), 1, cv2.LINE_AA)
            if imageNum == 0:
                cv2.putText(image, 'Get Ready', (200, 200),
                            cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 0), 4, cv2.LINE_AA)
                cv2.imshow('Image with landmarks', image)
                cv2.waitKey(3000)
            else:
                cv2.imshow('Image with landmarks', image)
                p = os.path.join('Azbuka', letter, str(imageNum))
                np.save(p, landmarkArray)
                cv2.waitKey(500)

            if cv2.waitKey(1) == ord('q') or cv2.getWindowProperty('Image with landmarks', cv2.WND_PROP_VISIBLE) < 1:
                break

    cap.release()
    cv2.destroyAllWindows()

KeyboardInterrupt: 

In [174]:
cap.release()
cv2.destroyAllWindows()

In [66]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [63]:
result_map = {key: num for num, key in enumerate(letters)}

In [64]:
sequences, results = [], []
for letter in letters:
    for imgNum in range(50):
        res = np.load(os.path.join('Azbuka', letter, "{}.npy".format(imgNum+1)))
        sequences.append(res) #ovime smo dobili listu nizova koji ce da predstavljaju ulaz
        results.append(result_map[letter]) #ovime smo dobili listu rezultata koji odgovaraju nizovima iz predhodne linije

In [68]:
x = np.array(sequences, object)
y = to_categorical(results).astype(int)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.05)

# Model

In [70]:
x_train.shape

(190, 126)

In [71]:
y_train.shape

(190, 4)

In [118]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import TensorBoard

In [82]:
log_dir = os.path.join('Logs')
tb_callback=TensorBoard(log_dir=log_dir)

In [163]:
model = Sequential()
model.add(Dense(256, activation='selu', input_dim=126))
model.add(Dropout(0.5))
model.add(Dense(128, activation='selu'))
model.add(Dropout(0.5))
model.add(Dense(64, activation='selu'))
model.add(Dropout(0.5))
model.add(Dense(4, activation='softmax'))

In [164]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [165]:
x_train = x_train.astype(np.float32)
x_test = x_test.astype(np.float32)

In [166]:
model.fit(x_train, y_train, epochs=300, callbacks=[tb_callback])

Epoch 1/300
6/6 [==============================] - 1s 6ms/step - loss: 2.5835 - categorical_accuracy: 0.2895
Epoch 2/300
6/6 [==============================] - 0s 3ms/step - loss: 1.6957 - categorical_accuracy: 0.4421
Epoch 3/300
6/6 [==============================] - 0s 6ms/step - loss: 1.4165 - categorical_accuracy: 0.5316
Epoch 4/300
6/6 [==============================] - 0s 6ms/step - loss: 1.1111 - categorical_accuracy: 0.6263
Epoch 5/300
6/6 [==============================] - 0s 6ms/step - loss: 0.9689 - categorical_accuracy: 0.6474
Epoch 6/300
6/6 [==============================] - 0s 6ms/step - loss: 0.8661 - categorical_accuracy: 0.6684
Epoch 7/300
6/6 [==============================] - 0s 6ms/step - loss: 0.7736 - categorical_accuracy: 0.6895
Epoch 8/300
6/6 [==============================] - 0s 2ms/step - loss: 0.6423 - categorical_accuracy: 0.7368
Epoch 9/300
6/6 [==============================] - 0s 3ms/step - loss: 0.6286 - categorical_accuracy: 0.7263
Epoch 10/300
6/6 [=

In [147]:
model.save("signLanguage.h5")

In [148]:
res=model.predict(x_test)

1/1 [==============================] - 0s 16ms/step


In [156]:
letters[np.argmax(res[3])]

'G'

In [155]:
letters[np.argmax(y_test[3])]

'G'

In [113]:
import random

# Glavni Deo Projekta

In [181]:
current_letter = random.choice(letters)
gesture_detected = False
threshold = 0.999
sequence=""
cap = cv2.VideoCapture(0)
with mp_holistics.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():
        _, image = cap.read()
        points, landmarkArray = buildLandmarkArray(image, holistic)

        landmarksOnScreen(image, points)
        
        cv2.putText(image, 'Letter ' + current_letter, (30, 30),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 0), 1, cv2.LINE_AA)
        cv2.putText(image, sequence, (500, 30),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 0), 1, cv2.LINE_AA)
        
        res = model.predict(np.expand_dims(landmarkArray, axis=0))[0]
        
        if res[np.argmax(res)] > threshold:
            if(letters[np.argmax(res)]==current_letter):
                cv2.putText(image, 'Correct ' + current_letter, (200, 200),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 1, cv2.LINE_AA)
                cv2.imshow('Image with landmarks', image)
                cv2.waitKey(2000)
                current_letter = random.choice(letters)
                gesture_detected = False
            else:
                cv2.imshow('Image with landmarks', image)
        else:
            cv2.imshow('Image with landmarks', image)

        if cv2.waitKey(1) == ord('q') or cv2.getWindowProperty('Image with landmarks', cv2.WND_PROP_VISIBLE) < 1:
            break

    cap.release()
    cv2.destroyAllWindows()

1/1 [==============================] - 0s 16ms/step


1/1 [==============================] - 0s 31ms/step


1/1 [==============================] - 0s 26ms/step


1/1 [==============================] - 0s 23ms/step


1/1 [==============================] - 0s 11ms/step


1/1 [==============================] - 0s 16ms/step


1/1 [==============================] - 0s 16ms/step


1/1 [==============================] - 0s 16ms/step


In [180]:
cap.release()
cv2.destroyAllWindows()